fix(ui): remove unneeded `aria-label` from `NavToggleButton`
frameless/strapi pull request #529
Opened 2024-03-19 11:55 UTC by AliKdhim87

The button already has descriptive text so `aria-label` is not needed

2024-03-19 13:29 UTC, bddjong approved these changes

2024-03-19 19:47 UTC, savitris requested changes
Ik heb deze branch lokaal bekeken maar zie nog steeds de aria-label als ik de knop inspecteer:
<img width="613" alt="Html code from a button showing it has an aria label" src="https://github.com/frameless/strapi/assets/11764984/696b78de-3b90-464c-b2b9-ad0584271717">
Is er iets dat ik ben fout aan het loaden?

2024-03-20 08:38 UTC, AliKdhim87 commented
> Ik heb deze branch lokaal bekeken maar zie nog steeds de aria-label als ik de knop inspecteer: <img alt="Html code from a button showing it has an aria label" width="613" src="https://private-user-images.githubusercontent.com/11764984/314206773-696b78de-3b90-464c-b2b9-ad0584271717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjQwMzIsIm5iZiI6MTcxMDkyMzczMiwicGF0aCI6Ii8xMTc2NDk4NC8zMTQyMDY3NzMtNjk2Yjc4ZGUtM2I5MC00NjRjLWIyYjktYWQwNTg0MjcxNzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YjBiNjIyOThjOWVlNGQ0MmYyMmI3NjY2M2JlN2ZhYTkwNjdhN2ViOGQzNzRhYWYwYWVmNDkzMzc0MDgyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.INY3ccuACJqAWea3SCBaCZaZI-kgJOdVMsRBzH23spQ"> Is er iets dat ik ben fout aan het loaden?

Heb je eerst het UI-pakket gebouwd?

```shell

yarn workspace @frameless/ui build
```

2024-03-20 10:12 UTC, savitris approved these changes

2024-03-20 10:22 UTC, merged