Fix inconsistent behavior of skip links
frameless/strapi pull request #713
Opened 2024-05-07 15:20 UTC by AliKdhim87

2024-05-08 09:08 UTC, Robbert requested changes

2024-05-08 09:08 UTC, Robbert commented on packages/ui/src/components/Navigation/NavigationList/index.tsx
> +        })}
Kan deze `id` niet op de container?
Eventueel kun je de container `tabIndex={-1}` geven en `onFocus()` met `firstItem.ref.current.focus()` de focus verplaatsen?

2024-05-08 10:41 UTC, AliKdhim87 commented on apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx
> +                <SkipLink href="#breadcrumb">{t('components.skip-link.main')}</SkipLink>
Ik ben het met je eens over het gebruik van de skip link. Deze zou de gebruiker moeten doorverwijzen naar de main tag in plaats van de Breadcrumb-component als we deze generiek willen houden.

Wat betreft de tweede vraag of alle pagina's een main tag hebben, gebaseerd op onze implementatie moeten alle pagina's inderdaad een main tag hebben, omdat we de [NEXTJS APP-router](https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#layouts) aanpak gebruiken, namelijk de [layout.tsx](https://github.com/frameless/strapi/blob/main/apps/pdc-frontend/src/app/%5Blocale%5D/(rootLayout)/layout.tsx#L207) die automatisch alle pagina's omhult.

2024-05-13 13:01 UTC, Robbert reviewed
Handig dat filmpje!! Heel blij mee

2024-05-13 15:59 UTC, Robbert approved these changes

2024-05-13 15:59 UTC, merged