feat: translate the English terms in URLs to Dutch language
frameless/strapi pull request #899
Opened 2024-09-06 13:40 UTC by AliKdhim87

2024-09-10 06:06 UTC, Robbert requested changes

2024-09-10 06:06 UTC, Robbert commented on apps/pdc-frontend/src/components/SearchBar/index.tsx
> +    defaultValue: 'zoeken',
Zou je de URL segment strings willen verzamelen in één file, of één file per locale, en importeren? `import { SearchSegment } from 'UrlSegmentNL`;`

Als je voor de URL utility functions kiest, dan moet het misschien net iets anders werken.

2024-09-10 06:06 UTC, Robbert commented on apps/pdc-frontend/src/app/[locale]/(rootLayout)/page.tsx
> +      href: !isAvailable ? undefined : `${productsSegment}/${alphabetSegment}/${letter.toLocaleLowerCase()}`,
Wat zou je er van denken om een file te hebben met utility functions om URLs te genereren? Uiteindelijk zouden we die kunnen delen tussen pdc-dashboard en pdc-frontend.

Bijvoorbeeld: `createProductUrl({ locale: 'en', product: 'klacht' })`.

Eventueel met base URL argument zoals `new URL(url, base)`:

`createProductUrl({ locale: 'en', product: 'klacht' }, process.env.PDC_FRONTEND_URL)`

2025-03-25 12:58 UTC, bddjong approved these changes
Ziet er goed uit als Robbert ook tevreden is met de verwerking van zijn feedback

2025-03-26 08:44 UTC, Robbert requested changes
to be continued

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/app/[locale]/(rootLayout)/not-found.tsx
> +    url: getStrapiGraphqlURL() as string,
Ik zou dit niet oplossen met een type cast. Je kunt beter de garantie geven dat de functie altijd een string als return waarde heeft.

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/app/actions/index.ts
> +    url: url?.href as string,
Garandeer een string

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/app/actions/index.ts
> +    url: url?.href as string,
garandeer een string

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/app/api/current-pathname/route.ts
> +    url: getStrapiGraphqlURL() as string,
garandeer een string

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/util/getAlphabeticallyProductsByLetter.ts
> +      url: getStrapiGraphqlURL() as string,
Garandeer een string

2025-03-26 08:44 UTC, Robbert commented on apps/pdc-frontend/src/util/getImageBaseUrl.ts
> +export const getImageBaseUrl = (segment?: string) => {
Garandeer een string: `(segment?: string): string`

2025-03-27 08:44 UTC, Robbert approved these changes

2025-03-27 09:41 UTC, merged